config:
  backup: true
  banner: true
  create: true
  dotpath: dotfiles
  keepdot: false
  link_dotfile_default: nolink
  link_on_import: nolink
  longkey: false
dotfiles:
  f_tmux.conf:
    src: tmux.conf
    dst: ~/.tmux.conf
  d_nvim:
    src: config/nvim
    dst: ~/.config/nvim
profiles:
  arch:
    dotfiles:
    - f_tmux.conf
    - d_nvim
